---
title: "HW3_poz3615"
author: "Piper Zimmerman"
date: "September 23, 2021"
output: pdf_document
---

```{r echo=FALSE}
library(data.table)
library(curl)
library(ggplot2)
library(ggpubr)
covid_raw <- fread("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv")
us <- covid_raw[covid_raw$countriesAndTerritories == 'United_States_of_America',]
us_filtered <- us[us$month %in% c(6:7),]
us_filtered$index <- rev(1:dim(us_filtered)[1]) 
fit<-lm(`Cumulative_number_for_14_days_of_COVID-19_cases_per_100000`~index, data=us_filtered)

## augment the data as previous
library(broom)
fit.diags <- broom::augment(fit)
plot1<-ggplot(fit, aes(x = .fitted, y = .resid)) + geom_point(color='slateblue2')+theme_classic()+labs(title="Residuals and Fitted")
plot2<-ggplot(fit, aes(sample=.resid))+stat_qq(color='indianred1')+theme_classic()+labs(title="Normal QQ")
plot3<-ggplot(fit, aes(.fitted, sqrt(abs(.stdresid))))+geom_point(color='aquamarine3')+theme_classic()+labs(title="Scale-Location")
plot4<-ggplot(fit, aes(.hat, .stdresid))+geom_point(color='slategray2')+theme_classic()+labs(title="Residuals and Leverage")
ggarrange(plot1,plot2,plot3,plot4,nrow=2)
```

\textbf{Appendix}
```{r eval=FALSE}
library(data.table)
library(curl)
library(ggplot2)
library(ggpubr)
covid_raw <- fread("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv")
us <- covid_raw[covid_raw$countriesAndTerritories == 'United_States_of_America',]
us_filtered <- us[us$month %in% c(6:7),]
us_filtered$index <- rev(1:dim(us_filtered)[1]) 
fit<-lm(`Cumulative_number_for_14_days_of_COVID-19_cases_per_100000`~index, data=us_filtered)

## augment the data as previous
library(broom)
fit.diags <- broom::augment(fit)
plot1<-ggplot(fit, aes(x = .fitted, y = .resid)) + geom_point(color='slateblue2')+theme_classic()+labs(title="Residuals and Fitted")
plot2<-ggplot(fit, aes(sample=.resid))+stat_qq(color='indianred1')+theme_classic()+labs(title="Normal QQ")
plot3<-ggplot(fit, aes(.fitted, sqrt(abs(.stdresid))))+geom_point(color='aquamarine3')+theme_classic()+labs(title="Scale-Location")
plot4<-ggplot(fit, aes(.hat, .stdresid))+geom_point(color='slategray2')+theme_classic()+labs(title="Residuals and Leverage")
ggarrange(plot1,plot2,plot3,plot4,nrow=2)
```